/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Artalk: typeof import('./theme/components/Artalk.vue')['default']
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    Layout: typeof import('./theme/components/Layout.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
  }
}
